# Generated by Django 2.2 on 2019-05-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='Designates whether the user can upload product or not.', verbose_name='seller status'),
        ),
    ]
