# Generated by Django 2.2 on 2019-05-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productcourse', '0002_auto_20190530_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled',
            name='payment_id',
        ),
    ]
