# Generated by Django 2.2 on 2019-05-30 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productcourse', '0003_remove_enrolled_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled',
            name='payment_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='productcourse.Payment'),
        ),
    ]
