# Generated by Django 2.2 on 2019-06-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcourse', '0005_auto_20190601_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
