# Generated by Django 2.2 on 2019-06-01 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productcourse', '0006_video_is_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user_id',
        ),
    ]
