# Generated by Django 2.2 on 2019-06-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productcourse', '0008_cart_questions_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='Course_id',
            new_name='course_id',
        ),
    ]
