# Generated by Django 2.2 on 2019-06-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcourse', '0010_auto_20190618_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_preview',
        ),
        migrations.AddField(
            model_name='course',
            name='course_tools_required',
            field=models.TextField(default='None'),
        ),
    ]
