# Generated by Django 2.2 on 2019-06-20 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productcourse', '0011_auto_20190620_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled',
            name='course_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='productcourse.Course'),
        ),
    ]
