# Generated by Django 2.2 on 2019-07-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcourse', '0019_course_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cat_logo',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
