# Generated by Django 2.2 on 2019-07-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productcourse', '0020_categories_cat_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='rating',
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('product_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='productcourse.Product')),
            ],
        ),
    ]
