# Generated by Django 2.2 on 2019-07-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productcourse', '0023_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='product_id',
        ),
    ]
