# Generated by Django 2.2 on 2019-07-24 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productcourse', '0025_cart_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user_id', 'product_id')},
        ),
    ]
