# Generated by Django 2.2 on 2019-08-01 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productcourse', '0026_auto_20190724_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='course_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='productcourse.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('user_id', 'course_id')},
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=255)),
                ('course_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='productcourse.Course')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('course_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='productcourse.Course')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
